### ISSUE TITLE
theme material bootstrap

### ISSUE THREAD

**Issue by c-jacquin** [AmbientIT/website#26]
perso je trouve joli t'en dis quoi ?

**Comment by couzic** [comment]
OUI !!!

## 

Mikael Couzic
32, rue du Javelot
Appartement 131
75013 Paris
06 51 17 97 83
09 54 90 02 55

2015-07-10 13:10 GMT+02:00 Charles Jacquin notifications@github.com:

**Comment by couzic** [comment]
On valide
