### ISSUE TITLE
[NEED] Envoi de mail depuis le formulaire de Contact & Devis

### ISSUE THREAD

**Issue by JeremieBALDY** [AmbientIT/website#36]
Action:
Configurer l'envoi de mail depuis le formulaire de contact / devis

Enjeu:
Recevoir par mails les contacts prospects

Description:
Utiliser le service SendGrid que je viens de configurer
https://azure.microsoft.com/fr-fr/documentation/articles/store-sendgrid-mobile-services-send-email-scripts/
De ce que je comprends on peut l'attaquer en REST

Config: (envoyé par mail)
smtp.sendgrid.net

**Comment by c-jacquin** [comment]
ca a marcher une fois et depuis plus rien ... il ya peut etre un truc a regler sur le dashboard sendgrid
