### ISSUE TITLE
[BUG] Blocage de le la page de contact après validation

### ISSUE THREAD

**Issue by JeremieBALDY** [AmbientIT/website#39]
Reproduire:
Lors de la validation du contact, si j'attends que le popup qui s'affiche 3 secondes s'en aille, la page est grisée et on ne peut plus rien faire (overlay non relâché)

**Comment by c-jacquin** [comment]
J'ai fait en sorte que le popup ne puisse plus sen aller ;à (c'est un peu de la triche mais on va dire que ca passe) les modif ne sont pas visible pour l'instant, je deploie ce soir
