### ISSUE TITLE
[NEED] Télécharger Descriptif du cours en PDF

### ISSUE THREAD

**Issue by JeremieBALDY** [AmbientIT/website#40]
Besoin:
Télécharger Descriptif du cours en PDF sur la page d'une formation

Enjeu:
Pouvoir laisser le candidat envoyer le PDF à son responsable / Pole Emploi

Requirement:
Si c'est possible de générer le PDF directement depuis la page HTML ce serait la cerise qui a son gâteau sur les bras

Exemple:
http://www.zenika.com/ressources_formation/fiche_formation/formation_java_zenika.pdf

**Comment by c-jacquin** [comment]
lol normalement pas de soucis pour faire ca depuis le client, si c trop galere je mettrai ca sur le webservice

**Comment by c-jacquin** [comment]
finalement c le serveur qui s'en charge, les pdf sont genere a la creation d'une formation en base et regenere a chaque mise à jour.

avantage : ca dl instant
inconvenient : temps de reponse plus long a la creation d'une formation, dependance sur le serveur

**Comment by c-jacquin** [comment]
Pour le template des pdf c du html, du coup c pas compliquer de trouver un truc sympa et de modifier

**Comment by JeremieBALDY** [comment]
Nickel Charles, je pense que c'est la meilleure solution.
