### ISSUE TITLE
formulaire de contact

### ISSUE THREAD

**Issue by c-jacquin** [AmbientIT/website#5]
template contact.ejs

civilité ?,
nom => required,
société,
un select avec nos formations => required,
textarea description du besoin => required max=500,
email => required,

ajax ?? (je dis oui !!)

angular et ngmessages ?? (oui ?)
 post /api/contact

bootstrap

**Comment by couzic** [comment]
Première version : 2a85f8790da3134ec9ef13675811083da0ce82a4

Il reste une petite marge de progression concernant le formulaire et sa validation. Pour être utilisable, il faut au minimum créer la partie backend pour l'envoi des mails.

**Comment by c-jacquin** [comment]
ok bien ouej !! je verrais bien un select a choix multiple pour les formations.
et je pense que ca serait propre que les messages d'erreur s'affiche au submit egalement (les required), pour ca il faut enlver ngdisabled et utilser ngsubmitted

**Comment by c-jacquin** [comment]
radio button civilité

**Comment by c-jacquin** [comment]
ajouter un spinner en attendant que la réponse arrive

**Comment by c-jacquin** [comment]
et embélir le reste de la page c'est degoulasse
